version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGODB_USER: "root"
      MONGODB_DATABASE: "pg"
      MONGODB_PASS: "root"
    ports: 
      - "${MONGO_PORT}:27017"
    volumes:
      - data:/data/db
    networks:
      - app-network
  backend_learn-ember:
    container_name: backend_learn-ember
    restart: unless-stopped
    build: ./backend
    depends_on: 
      - mongo
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - /usr/src/node_modules/
      - ./backend:/usr/src
    networks:
      - app-network

volumes: 
  data:

networks:
  app-network:
    driver: bridge
  default:
    name: learn-ember