version: "3.7"

services:
  backend_learn-ember:
    container_name: backend_learn-ember
    restart: unless-stopped
    build: ./backend
    ports:
      - "${APP_PORT}:3000"
      - "9229:9229"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - /usr/src/node_modules/
      - ./backend:/usr/src
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports: 
      - "${MONGO_PORT}:27017"
    volumes:
      - data:/data/db 

volumes: 
  data:

networks:
  default:
    name: learn-ember